In [102]:
#Library Imports
import requests
import pandas as pd

!pip -q install requests tqdm

import os
import json
from urllib.parse import urlencode

import requests
import pandas as pd
from tqdm import tqdm
import json

!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\samft\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in c:\users\samft\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\samft\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\samft\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\samft\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\samft\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from requests->vaderSentiment) (2025.11.12)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\samft\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [12]:
video_ids = {"Warriors-2014":"fmI_Ndrxy14",
             "World_Collide-2015":"4Twd965VzX4",
             "Ignite-2016":"Zasx9hjo4WY",
             "Legends_Never_Die-2017":"4Q46xYqUwZQ",
             "Rise-2018":"fB8TyLTD7EE",
             "Phoenix-2019":"i1IKnWDecwA",
             "Take_Over-2020":"KbNL9ZyB49c",
             "Burn_It_Down-2021":"1Z6CHioIn3s",
             "Star_Walkin-2022":"HYsz1hP0BFo",
             "Gods-2023":"C3GouGa0noM",
             "Heavy_Is_The_Crown-2024":"5FrhtahQiRc",
             "Sacrifice-2025":"pzt6SmvGpXk"
             }

In [13]:
#API Key Security

import os
from getpass import getpass

# Paste your API key when prompted (input will be hidden in Colab)
os.environ["YOUTUBE_API_KEY"] = getpass("Paste your API Key: ")

#Youtube Key (Delete Later): AIzaSyDGTRnCDz7YKB6l7nf7JZEgEqRALS2dvJ4

In [20]:
API_KEY = os.environ.get("YOUTUBE_API_KEY")
BASE_URL = "https://www.googleapis.com/youtube/v3"

In [106]:
#Comment Scraping Function

def get_comments(video_id, max_comments = 100):
    url = f"{BASE_URL}/commentThreads"

    params = {"part": "snippet",
              "videoId": video_id,
              "key": API_KEY,
              "maxResults": 100,
              "textFormat": "plainText",
              "order": "relevance"
              }
    
    response = requests.get(url, params = params)
    data = response.json()

    
    comments = []

    for item in data.get("items",[]):
        snippet = item["snippet"]["topLevelComment"]["snippet"]
        comments.append({"text": snippet["textOriginal"],
                         "author": snippet["authorDisplayName"],
                         "like_count": snippet["likeCount"]})
    
    return comments

In [107]:
all_comments = []

for name,video_code in video_ids.items():
    comments = get_comments(video_code)
    
    for c in comments:
        c["video_name"] = name

    all_comments.extend(comments)

In [122]:
#Creating DataFrame

df = pd.DataFrame(all_comments)

df["year"] = df["video_name"].str.split("-").str[-1]
df["year"] = df["year"].astype(int)

df["video_name"] = df["video_name"].str.split("-").str[0]
df["video_name"] = df["video_name"].str.replace("_"," ")
df.sample(10)

,text,author,like_count,video_name,year
303,8 years later. If you still listen to this son...,@Nozomi600,236,Legends Never Die,2017
739,3:06 - 3:08 how the character's hits lined up ...,@SamDVisual,69,Burn It Down,2021
893,25월즈 뮤비 보고 오신분..? 이제 스타워킨은 명곡 오브 명곡의 반열에 오른 듯,@dmwriter,8,Star Walkin,2022
762,Respect to Chovy for Qualifying Worlds three t...,@griffindawg,1961,Burn It Down,2021
332,the fact that this was 3 years ago and everyon...,@starrainqq,1593,Legends Never Die,2017
857,“명작은 그 전개와 결말을 알고서도 다시 찾게 만든다”,@lililil-j8h1n,21,Star Walkin,2022
294,"hype about this years worlds, listening to eve...",@janaedits1695,360,Ignite,2016
315,Ain't NO WAY this banger was made for a game 😭,@ocexngxmy2411,933,Legends Never Die,2017
722,I appreciate them so much for doing these ever...,@Scyrina,3400,Burn It Down,2021
33,2014: Nice song\r\n2024: Nice song,@WASB,1783,Warriors,2014

In [123]:
#Sentiment Analysis
sia = SentimentIntensityAnalyzer()
df["sentiment"] = df["text"].apply(lambda x: sia.polarity_scores(x)["compound"])
df.sample(20)

,text,author,like_count,video_name,year,sentiment
684,Riot: Everything will sell if there is Faker i...,@katsumiminami3264,7581,Take Over,2020,-0.5574
1193,한국 T1 팬들만 뿔난게 아니네 십 ㅋㅋㅋㅋㅋ 외국인 형님들까지 한마음한뜻이네 그냥,@subinheo,392,Sacrifice,2025,0.0000
181,LPL만 남을 뻔한 어두운 하늘을 불태우고 거인이 된 2023 T1.,@STONEHEARTHWILLRETURN,7,World Collide,2015,0.0000
1027,진짜 이게 재평가 받을줄 몰랐다,@뇨무무,49,Heavy Is The Crown,2024,0.0000
157,"getting hyped for 2019 with RISE, Worlds colli...",@mtgplayer1239,32,World Collide,2015,0.4833
1145,구마유시를 위한 노래였나봐요..,@연화-p3z,18,Sacrifice,2025,0.0000
930,Who returns from MV 2025 👍,@Loyopiuu,31,Gods,2023,0.0000
874,The song is really good but I can already tell...,@zenvious5645,1868,Star Walkin,2022,0.2724
752,🔥🔥🔥Let's go LCK DKWIN/ GENWIN/ T1WIN/ HLEWIN 🔥🔥🔥,@LCK,4845,Burn It Down,2021,-0.8750
917,올해 뮤비보고 정신혼미해져서 다시온 롤붕이들은 개추 ㅋㅋ,@케빈더브라위너17,1393,Gods,2023,0.0000
1092,"말탄 데프트, 얼굴에 점찍고 변신한 데프트, 안경쓴 데프트, 노란머리 데프트, 깃털...",@Chasey-u6r,2887,Heavy Is The Crown,2024,0.0000
1019,진지하게 이 곡이 재평가되는 날이 올줄은.... ㅋㅋㅋㅋㅋㅋ 이번 월즈 주제곡에 비...,@WK_Mashiro,485,Heavy Is The Crown,2024,0.0000
987,I was so skeptical about NewJeans singing a so...,@ilovemydonkey,1222,Gods,2023,-0.8900
252,I have to admit I fell in love with this track...,@InstaSound,1569,Ignite,2016,0.4019
533,“Are you gonna die today?”\n\n\n\nAlly Yasuo P...,@nan3606,12162,Phoenix,2019,-0.2960
486,"I dont care what some people say, i loved this...",@II_ReAl_II,161,Rise,2018,0.9033
472,League of Legends is my favorite anime,@markevans2797,2557,Rise,2018,0.4588
339,"I don't even play LOL , but wow... this song i...",@dgNoah,923,Legends Never Die,2017,0.8479
924,2024 월즈 곡 듣고 'GODS는 시발 이렇게 잘만들어놓고' 라는 생각으로 다시 ...,@ON-fe8ju,9794,Gods,2023,0.0000
938,今年是2025年11月9日，恭喜T13:2战胜KT，多兰成为这个MV里面最后一个夺冠的选手！！,@yohanceqin7135,31,Gods,2023,0.0000